%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
% Detects the first year with an ice-free month for all SSP experiments
% Saves it in a structure Model - Ensemble - each experiment
% Ice-free defined as SIA <= 1E12
% If no value can be found, set to -1
% Reads the metadata from SIA2023_all.xlsx, generated by detect_2023.m, for
% consistency between the figures at a later stage
%
% For the subselection of models listed in Models_v1.xlsx that has
% Column 1: Models [string]
% Column 2: Ref, reference date for that model's format, as YYYYMMDD [int]
% Column 3: YearLength, number of days in a year for that model [int]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

matref=readtable('SIA2023_all.xlsx');
matdaily=struct('Models',[],'Ensembles',[],'Date_ssp119',[],'Date_ssp126',[],...
    'Date_ssp245',[],'Date_ssp370',[],'Date_ssp585',[]);
sspZ={'ssp119';'ssp126';'ssp245';'ssp370';'ssp585'};

AA=readtable('Models_v1.xlsx');


for ipos=1:size(matref,1)
    matdaily(ipos,1).Models=matref.Models(ipos);
    matdaily(ipos,1).Ensembles=matref.Ensembles(ipos);
    posAA=find(strcmp(AA.Models,char(matref.Models(ipos))));
    for issp=1:length(sspZ)
        fileZ=dir([char(matref.Models(ipos)) '_' char(matref.Ensembles(ipos)) '_' sspZ{issp} '_*.csv']);
        if ~isempty(fileZ)
            T=readtable(fileZ(1).name);
                if ~isempty(find(~isnan(T.SIA_mon) & ~isinf(T.SIA_mon) & T.SIA_mon<1E15))
                    pos=find(T.SIA_mon<1E12,1,'first'); junk=-1;
                    if ~isempty(pos)
                        junk=floor(T.Time_mon(pos)/100);
                    end                    
            eval(sprintf('matdaily(ipos,1).Date_%s=junk;',sspZ{issp}));
            clear pos T pos2023 junk
                end
        end
        clear fileZ
    end
    clear posAA
end



